// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCAN1Lt5kIogUtq5qja_6KrIuKOfIi0rg',
    appId: '1:695328846988:web:3fe381c64f979bb71c37a9',
    messagingSenderId: '695328846988',
    projectId: 'lecture-lift',
    authDomain: 'lecture-lift.firebaseapp.com',
    storageBucket: 'lecture-lift.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJZIQAEtM7v1VFst2OsmhaIp2akKLwDAQ',
    appId: '1:695328846988:android:32ca98e6625e58841c37a9',
    messagingSenderId: '695328846988',
    projectId: 'lecture-lift',
    storageBucket: 'lecture-lift.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF25IRim3xN_pjQImVj-WIHuCe7pnT3yo',
    appId: '1:695328846988:ios:d4d0715e0cc1a8e11c37a9',
    messagingSenderId: '695328846988',
    projectId: 'lecture-lift',
    storageBucket: 'lecture-lift.firebasestorage.app',
    iosBundleId: 'com.bayla.lectureLift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF25IRim3xN_pjQImVj-WIHuCe7pnT3yo',
    appId: '1:695328846988:ios:c97ff842dce4210f1c37a9',
    messagingSenderId: '695328846988',
    projectId: 'lecture-lift',
    storageBucket: 'lecture-lift.firebasestorage.app',
    iosBundleId: 'com.example.lectureLift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCAN1Lt5kIogUtq5qja_6KrIuKOfIi0rg',
    appId: '1:695328846988:web:0112fbd47ff2e40e1c37a9',
    messagingSenderId: '695328846988',
    projectId: 'lecture-lift',
    authDomain: 'lecture-lift.firebaseapp.com',
    storageBucket: 'lecture-lift.firebasestorage.app',
  );
}
